### ISSUE TITLE
breaking change of Jaro-winkler boost

### ISSUE THREAD

**Issue by jqnatividad** [rapidfuzz/strsim-rs#68]
First off, thanks for thanks for updating the library after a long time @dguo @maxbachmann !

However, shouldn't the latest release be a minor version release and not a patch release given the breaking change introduced by changing the Jaro Winkler boost?

That is, shouldn't the latest release be 0.11.0 and not 0.10.1?

**Comment by maxbachmann** [comment]
You are probably right. I janked the release and instead republished as `0.11.0`.
